version: '2'


services:
    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: dev_user
            MONGO_INITDB_ROOT_PASSWORD: dev_password
        ports:
            - "27017:27017"
        volumes:
            - ./container-volumes/mongo_db:/data/mongo_db
    
    # nginx:
    #     image: nginx:1.13
    #     container_name: nginx
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/nginx.conf

    auth:
        build: ./ms-auth
        image: ms-auth
        container_name: ms-auth
        ports:
            - "8000:8000"


networks:
    go_consistent:
        driver: bridge